// //Types for getting user type
export const USER_TYPE_REQUEST = 'USER_TYPE_REQUEST';
export const USER_TYPE_LIST = 'USER_TYPE_LIST';

//Types for Login
export const LOGIN_REQUEST_REQUEST = 'LOGIN_REQUEST_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAILURE = 'LOGIN_REQUEST_FAILURE';

export const PROVIDER_LOGIN_REQUEST = 'PROVIDER_LOGIN_REQUEST';
export const PROVIDER_LOGIN_SUCCESS = 'PROVIDER_LOGIN_SUCCESS';
export const PROVIDER_LOGIN_FAILURE = 'PROVIDER_LOGIN_FAILURE';
//Types for Logout
export const LOGOUT_REQUEST_REQUEST = 'LOGOUT_REQUEST_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_FAILURE = 'LOGOUT_REQUEST_FAILURE';

//Types for Social Login
export const SOCIAL_LOGIN_REQUEST = 'SOCIAL_LOGIN_REQUEST';
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_FAILURE = 'SOCIAL_LOGIN_FAILURE';

//Types for Sign up
export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAILURE = 'CUSTOMER_SIGNUP_FAILURE';

export const SERVICE_PROVIDER_SIGNUP_REQUEST =
  'SERVICE_PROVIDER_SIGNUP_REQUEST';

//Types for OTP Verification
export const OTP_VERIFY_REQUEST = 'OTP_VERIFY_REQUEST';
export const OTP_VERIFY_SUCCESS = 'OTP_VERIFY_SUCCESS';
export const OTP_VERIFY_FAILURE = 'OTP_VERIFY_FAILURE';

export const SIGNUP_OTP_VERIFY_REQUEST = 'SIGNUP_OTP_VERIFY_REQUEST';
export const SIGNUP_OTP_VERIFY_SUCCESS = 'SIGNUP_OTP_VERIFY_SUCCESS';
export const SIGNUP_OTP_VERIFY_FAILURE = 'SIGNUP_OTP_VERIFY_FAILURE';

//Types for  forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

//Types for reset password
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_FAILURE = 'PASSWORD_RESET_FAILURE';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

//Types for Walkthrough
export const SET_WALKTHROUGH_REQUEST = 'SET_WALKTHROUGH_REQUEST';
export const SET_WALKTHROUGH_SUCCESS = 'SET_WALKTHROUGH_SUCCESS';

//SET PROFILE IMAGE
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_PROFILE_IMAGE_REQUEST = 'SET_PROFILE_IMAGE_REQUEST';

//GET PROFILE
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

//UPDATE PROFILE
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

//GET PRIVACY POLICY
export const GET_PRIVACY_POLICY_REQUEST = 'GET_PRIVACY_POLICY_REQUEST';
export const GET_PRIVACY_POLICY_SUCCESS = 'GET_PRIVACY_POLICY_SUCCESS';
export const GET_PRIVACY_POLICY_FAILURE = 'GET_PRIVACY_POLICY_FAILURE';

//GET FAQ's
export const GET_FAQ_REQUEST = 'GET_FAQ_REQUEST';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILURE = 'GET_FAQ_FAILURE';

//GET TERMS & CONDITIONS
export const GET_TERMS_CONDITION_REQUEST = 'GET_TERMS_CONDITION_REQUEST';
export const GET_TERMS_CONDITION_SUCCESS = 'GET_TERMS_CONDITION_SUCCESS';
export const GET_TERMS_CONDITION_FAILURE = 'GET_TERMS_CONDITION_FAILURE';

export const ADD_KIDS_REQUEST = 'ADD_KIDS_REQUEST';
export const ADD_PETS_REQUEST = 'ADD_PETS_REQUEST';

// customer Appointment
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES';

export const GET_SERVICE_PROVIDERS_REQUEST = 'GET_SERVICE_PROVIDERS_REQUEST';
export const GET_SERVICE_PROVIDERS_SUCCESS = 'GET_SERVICE_PROVIDERS_SUCCESS';
export const GET_SERVICE_PROVIDERS_FAILURE = 'GET_SERVICE_PROVIDERS_FAILURE';

export const GET_SERVICE_PROVIDER_DETAILS_REQUEST =
  'GET_SERVICE_PROVIDER_DETAILS_REQUEST';

export const GET_SERVICE_PROVIDER_DETAILS_SUCCESS =
  'GET_SERVICE_PROVIDER_DETAILS_SUCCESS';

export const GET_SERVICE_PROVIDER_DETAILS_FAILURE =
  'GET_SERVICE_PROVIDER_DETAILS_FAILURE';
