// import {svgIcons} from '../../assets/svgs/index';
export const appLogos = {
  logo: require('../../assets/logos/applogo.png'),
};

export const appImages = {
  welcome1: require('../../assets/images/welcome1.png'),
  welcomeBg: require('../../assets/images/welcomeBg.png'),
  pana: require('../../assets/images/pana.png'),
  pana2: require('../../assets/images/pana2.png'),
  pana3: require('../../assets/images/pana3.png'),
  locationImg: require('../../assets/images/locationImg.png'),
  dogWalking: require('../../assets/images/dogWalking.png'),
  findBaby: require('../../assets/images/findBaby.png'),
  housekeeper: require('../../assets/images/housekeeper.png'),
  workingMom: require('../../assets/images/workingMom.png'),
  user: require('../../assets/images/user.png'),
  emoji: require('../../assets/images/emoji.png'),
  emoji2: require('../../assets/images/emoji2.png'),
  emoji3: require('../../assets/images/emoji3.png'),
  emoji4: require('../../assets/images/emoji4.png'),
  emoji5: require('../../assets/images/emoji5.png'),
  emoji6: require('../../assets/images/emoji6.png'),
  card: require('../../assets/images/card.png'),
  card2: require('../../assets/images/card2.png'),
};

export const appIcons = {
  google: require('../../assets/icons/google.png'),
  apple: require('../../assets/icons/apple.png'),
  facebook: require('../../assets/icons/facebook.png'),
  myBooking: require('../../assets/icons/myBooking.png'),
  home: require('../../assets/icons/home.png'),
  user: require('../../assets/icons/user.png'),
  notification: require('../../assets/icons/notification.png'),
  tabIcon: require('../../assets/icons/tabIcon.png'),
  filter: require('../../assets/icons/filter.png'),
  settings: require('../../assets/icons/settings.png'),
  photo: require('../../assets/icons/photo.png'),
  location: require('../../assets/icons/location.png'),
  bookmark: require('../../assets/icons/bookmark.png'),
  fillbookmark: require('../../assets/icons/fillbookmark.png'),
  unfillbookmark: require('../../assets/icons/unfillbookmark.png'),
  zoom: require('../../assets/icons/zoom.png'),
  star: require('../../assets/icons/star.png'),
  tackLine: require('../../assets/icons/trackLine.png'),
  circle: require('../../assets/icons/circle.png'),
  pencil: require('../../assets/icons/pencil.png'),
  user2: require('../../assets/icons/user2.png'),
  family: require('../../assets/icons/family.png'),
  book: require('../../assets/icons/book.png'),
  privacy: require('../../assets/icons/privacy.png'),
  terms: require('../../assets/icons/terms.png'),
  paymentcard: require('../../assets/icons/paymentcard.png'),
  oval: require('../../assets/icons/oval.png'),
  cardHome: require('../../assets/icons/cardHome.png'),
  simpleCard: require('../../assets/icons/simpleCard.png'),
  emptyStar: require('../../assets/icons/emptyStar.png'),
  sms: require('../../assets/icons/sms.png'),
  send: require('../../assets/icons/send.png'),
  vol: require('../../assets/icons/vol.png'),
  mic: require('../../assets/icons/mic.png'),
  checked: require('../../assets/icons/checked.png'),
  unChecked: require('../../assets/icons/unChecked.png'),
  tik: require('../../assets/icons/tik.png'),
  arrowIcon: require('../../assets/icons/arrowIcon.png'),
  droparrow: require('../../assets/icons/dropArrow.png'),
  dotted: require('../../assets/icons/dottedline.png'),
  cancel: require('../../assets/icons/cancel.png'),
  swipe: require('../../assets/icons/swipe.png'),
  pointer: require('../../assets/icons/pointer.png'),
  attach: require('../../assets/icons/attach.png'),
  menu: require('../../assets/icons/menu.png'),
  delete: require('../../assets/icons/delete.png'),
  added: require('../../assets/icons/added.png'),
  share: require('../../assets/icons/share.png'),
  plus: require('../../assets/icons/plus.png'),
  alertIcon: require('../../assets/icons/alert.png'),
};

export const appSvgs = {
  // ...svgIcons,
};
export const appJSON = {};
